import '@/theme/globals.scss';
import type { Metadata } from 'next';
import React from 'react';
import { fonts } from '@/theme/fonts';
import { routing } from '@/i18n/routing';

export const metadata: Metadata = {
  title: 'Donation Baza',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = Array.isArray(children) && children[0]?.props?.params?.locale;

  return (
    <html
      lang={locale ?? routing.defaultLocale}
      className={`${fonts.montserrat.variable}`}
    >
      <head>
        <link rel="icon" href="/favicon.ico" sizes="16x16" />
      </head>
      <body>{children}</body>
    </html>
  );
}
