import '@/theme/globals.scss';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import type { Metadata } from 'next';
import QueryClientProvider from '@/components/providers/QueryClientProvider';
import React from 'react';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { fonts } from '@/theme/fonts';

export const metadata: Metadata = {
  title: 'Donation Baza',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fonts.inter.variable} ${fonts.montserrat.variable}`}
    >
      <head>
        <link rel="icon" href="/favicon.ico" sizes="16x16" />
      </head>
      <body>
        <Header />
        <QueryClientProvider>
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>

        <Footer />
      </body>
    </html>
  );
}
