import '@/theme/globals.scss';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import type { Metadata } from 'next';
import React from 'react';
import RootProviders from '@/components/providers';
import { fonts } from '@/theme/fonts';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Donation Baza',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale} className={`${fonts.montserrat.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="16x16" />
      </head>
      <body>
        <RootProviders messages={messages} locale={locale}>
          <Header />
          {children}
          <Footer />
        </RootProviders>
      </body>
    </html>
  );
}
