import '@/theme/globals.scss';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';

import type { Metadata } from 'next';
import { ModalProvider } from '@/context/ModalContext';
import { NextIntlClientProvider } from 'next-intl';
import QueryClientProvider from '@/components/providers/QueryClientProvider';
import React from 'react';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { fonts } from '@/theme/fonts';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Donation Baza',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale} className={`${fonts.montserrat.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="16x16" />
      </head>
      <ModalProvider>
        <body>
          <NextIntlClientProvider messages={messages} locale={locale}>
            <QueryClientProvider>
              <Header />
              {children}
              <Footer />
              <ReactQueryDevtools initialIsOpen={false} />
            </QueryClientProvider>
          </NextIntlClientProvider>
        </body>
      </ModalProvider>
    </html>
  );
}
